print("====================")
print("   Moja vizitka ")
print("====================")
print("")
print("Meno: Vladimír")
print("Vek: 45")
print("Záluby: Kódovanie, čaj, fotografovanie, výlety, ...")
print("")
print("==========================================================")
